name: build_ErfanGSIs

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  ROM_URL: https://doc-14-74-docs.googleusercontent.com/docs/securesc/qjbtn09m5607muo98732a7dg2j71akpr/d6vdikj8h4cht2369m3hpt43u3rsss1u/1601182500000/10275588129933848950/13061163785555691354/1PlWh5V-bRjnEL34S7YW-HZ-QWFgqqiY0?e=download&authuser=0&nonce=a0ds286nb16b4&user=13061163785555691354&hash=49a96irvimo351p1hn9e96grj08r9m2g
  ROM_NAME: moto
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk wget
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/erfanoabdi/ErfanGSIs.git
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate GSI
         run: sudo ./ErfanGSIs/url2GSI.sh $ROM_URL $ROM_NAME
       
       - name: 7zip GSI_AB  
         run: |
              sudo apt-get install p7zip
              cd /home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs
              mkdir final
              7z a -t7z -r final/GSI_AB.7z ErfanGSIs/output/*AB*

        - name: Upload GSI_AB to WeTransfer
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet final/GSI_AB.7z
    
       
       - name: 7zip GSI_Aonly  
         run: |
              7z a -t7z -r final/GSI_Aonly.7z ErfanGSIs/output/*Aonly*
    
       - name: Upload GSI_Aonly to WeTransfer
         run: |
              ./transfer wet final/GSI_Aonly.7z 
            
